# generated by datamodel-codegen:
#   filename:  api-error.json

from __future__ import annotations
from enum import StrEnum
from pydantic import BaseModel, ConfigDict, Field


class Code(StrEnum):
    NOT_FOUND = "NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    RATE_LIMITED = "RATE_LIMITED"
    UPSTREAM_FAILED = "UPSTREAM_FAILED"
    INTERNAL = "INTERNAL"


class ApiError(BaseModel):
    """
    The `error` object in `{ ok: false, error }`. `message` is user-facing Hindi; `code` is for the client.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    code: Code
    message: str = Field(..., description="Hindi, shown to the user as-is.")
    suggestions: list[str] | None = Field(
        None,
        description="Only on NOT_FOUND from /lookup. The server always sends []; the app fills it from its local index by Levenshtein.",
    )
