# generated by datamodel-codegen:
#   filename:  context-index.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field


class ContextIndex(BaseModel):
    """
    Structured Outputs schema for the index-only context path (Phase 3 experiment): the model only classifies which sense applies; the Hindi note is pre-written per sense by the pipeline.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    senseIndex: int = Field(..., ge=0)
