# generated by datamodel-codegen:
#   filename:  dictionary-entry.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field


class BilingualPair(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: str
    hi: str


class Form(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: str = Field(..., description="The inflected form, lowercase.", min_length=1)
    label: str = Field(
        ...,
        description="Hindi label: बहुवचन | भूतकाल | वर्तमान (वह) | क्रिया-रूप | तुलनात्मक | उत्तमता | अमेरिकी वर्तनी ...",
    )
    hi: str


class Sense(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: int = Field(
        ..., description="Stable position in `senses`; the context resolver returns this.", ge=0
    )
    partOfSpeech: str = Field(
        ...,
        description="Hindi: संज्ञा | क्रिया | विशेषण | क्रियाविशेषण | सर्वनाम | पूर्वसर्ग | समुच्चयबोधक | विस्मयादिबोधक | मुहावरा",
    )
    meaning: str = Field(..., description="Hindi, short. The tooltip headline.", min_length=1)
    definition: str = Field(..., description="Hindi, one plain sentence.", min_length=1)
    examples: list[BilingualPair]


class DictionaryEntry(BaseModel):
    """
    One headword (or phrase) with its Hindi layer. Stored in Mongo `entries` with `_id = word`, and in the on-device SQLite as a JSON column.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    word: str = Field(
        ..., description="Lemma, lowercase. For phrases, the space-joined normalized tokens.", min_length=1
    )
    ipa: str = Field(
        ..., description="IPA transcription without surrounding slashes. Empty string when unknown."
    )
    hindiPronunciation: str = Field(
        ..., description="Devanagari transliteration of the English pronunciation, e.g. फ़ॉर्चून."
    )
    senses: list[Sense] = Field(..., min_length=1)
    synonyms: list[BilingualPair]
    antonyms: list[BilingualPair]
    forms: list[Form]
    isPhrase: bool
