# generated by datamodel-codegen:
#   filename:  entry-generation.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field


class BilingualPair(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: str
    hi: str


class Form(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: str = Field(..., min_length=1)
    label: str
    hi: str


class Sense(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: int = Field(..., ge=0)
    partOfSpeech: str
    meaning: str = Field(..., min_length=1)
    definition: str = Field(..., min_length=1)
    examples: list[BilingualPair]


class EntryGeneration(BaseModel):
    """
    What the pipeline's LLM pass returns for one headword: the Hindi layer only. The pipeline merges it with word/ipa/isPhrase from Wiktionary into a DictionaryEntry and validates that. `senses` must have exactly one item per input sense, in the same order, with matching `index` values — the model translates and explains the given senses and never adds, drops or reorders them. Definitions are duplicated from dictionary-entry.json (not $ref'd across files) because OpenAI strict mode needs a self-contained schema.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    hindiPronunciation: str = Field(
        ..., description="Devanagari transliteration of the English pronunciation, e.g. फ़ॉर्चून."
    )
    senses: list[Sense]
    synonyms: list[BilingualPair]
    antonyms: list[BilingualPair]
    forms: list[Form]
