# generated by datamodel-codegen:
#   filename:  phrase-match.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field


class PhraseMatch(BaseModel):
    """
    Result of POST /phrases/match when a multi-word phrase covers the tapped token. `start` + `tokenCount` tell the app which tokens to highlight.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    phrase: str = Field(..., description="The matched phrase as it appears in `phrases._id`.")
    lemma: str = Field(..., description="Key into `entries`.")
    start: int = Field(
        ..., description="Index of the first matched token in the submitted `tokens` array.", ge=0
    )
    tokenCount: int = Field(..., description="Number of consecutive tokens the phrase covers.", ge=2, le=4)
