# generated by datamodel-codegen:
#   filename:  sense-notes.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field


class Note(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: int = Field(..., ge=0)
    note: str = Field(..., description="Hindi, at most two short lines.")


class SenseNotes(BaseModel):
    """
    Pipeline output for the index-only context experiment: one pre-written Hindi contrast note per sense of a word, saying when this sense applies and what the word is NOT in that case. Stored in Mongo `senseNotes { _id: word, notes: string[] }` aligned with DictionaryEntry.senses by index.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    notes: list[Note]
