// GENERATED by tool/gen_models.py from contracts/schemas — do not edit.
// Regenerate: python3 tool/gen_models.py && dart run build_runner build -d

import 'package:freezed_annotation/freezed_annotation.dart';

part 'contracts.freezed.dart';
part 'contracts.g.dart';

/// One headword (or phrase) with its Hindi layer. Stored in Mongo `entries` with `_id = word`, and in the on-device SQLite as a JSON column.
@freezed
abstract class DictionaryEntry with _$DictionaryEntry {
  const factory DictionaryEntry({
    required String word,
    required String ipa,
    required String hindiPronunciation,
    required List<Sense> senses,
    required List<BilingualPair> synonyms,
    required List<BilingualPair> antonyms,
    required List<WordForm> forms,
    required bool isPhrase,
  }) = _DictionaryEntry;

  factory DictionaryEntry.fromJson(Map<String, dynamic> json) => _$DictionaryEntryFromJson(json);
}

@freezed
abstract class Sense with _$Sense {
  const factory Sense({
    required int index,
    required String partOfSpeech,
    required String meaning,
    required String definition,
    required List<BilingualPair> examples,
  }) = _Sense;

  factory Sense.fromJson(Map<String, dynamic> json) => _$SenseFromJson(json);
}

@freezed
abstract class BilingualPair with _$BilingualPair {
  const factory BilingualPair({
    required String en,
    required String hi,
  }) = _BilingualPair;

  factory BilingualPair.fromJson(Map<String, dynamic> json) => _$BilingualPairFromJson(json);
}

@freezed
abstract class WordForm with _$WordForm {
  const factory WordForm({
    required String en,
    required String label,
    required String hi,
  }) = _WordForm;

  factory WordForm.fromJson(Map<String, dynamic> json) => _$WordFormFromJson(json);
}

/// Which sense of a word applies in one sentence. Also the exact Structured Outputs schema for the live /context model call.
@freezed
abstract class ContextResult with _$ContextResult {
  const factory ContextResult({
    required int senseIndex,
    required String meaning,
    required String note,
  }) = _ContextResult;

  factory ContextResult.fromJson(Map<String, dynamic> json) => _$ContextResultFromJson(json);
}

/// Full-sentence translation. Streamed over SSE in field order: hindi, simpleMeaning, difficultWords.
@freezed
abstract class TranslationResult with _$TranslationResult {
  const factory TranslationResult({
    required String source,
    required String hindi,
    required String simpleMeaning,
    required List<TranslationResultDifficultWords> difficultWords,
  }) = _TranslationResult;

  factory TranslationResult.fromJson(Map<String, dynamic> json) => _$TranslationResultFromJson(json);
}

@freezed
abstract class TranslationResultDifficultWords with _$TranslationResultDifficultWords {
  const factory TranslationResultDifficultWords({
    required String en,
    required String hi,
  }) = _TranslationResultDifficultWords;

  factory TranslationResultDifficultWords.fromJson(Map<String, dynamic> json) => _$TranslationResultDifficultWordsFromJson(json);
}

/// Result of POST /phrases/match when a multi-word phrase covers the tapped token. `start` + `tokenCount` tell the app which tokens to highlight.
@freezed
abstract class PhraseMatch with _$PhraseMatch {
  const factory PhraseMatch({
    required String phrase,
    required String lemma,
    required int start,
    required int tokenCount,
  }) = _PhraseMatch;

  factory PhraseMatch.fromJson(Map<String, dynamic> json) => _$PhraseMatchFromJson(json);
}

/// The `error` object in `{ ok: false, error }`. `message` is user-facing Hindi; `code` is for the client.
@freezed
abstract class ApiError with _$ApiError {
  const factory ApiError({
    required ApiErrorCode code,
    required String message,
    List<String>? suggestions,
  }) = _ApiError;

  factory ApiError.fromJson(Map<String, dynamic> json) => _$ApiErrorFromJson(json);
}

enum ApiErrorCode {
  @JsonValue('NOT_FOUND')
  notFound,
  @JsonValue('BAD_REQUEST')
  badRequest,
  @JsonValue('RATE_LIMITED')
  rateLimited,
  @JsonValue('UPSTREAM_FAILED')
  upstreamFailed,
  @JsonValue('INTERNAL')
  internal,
}
