#!/usr/bin/env python3
"""Generate lib/core/models/contracts.dart (freezed + json_serializable) from contracts/schemas.

    python3 tool/gen_models.py && dart run build_runner build -d

Never hand-edit the output. Supports the subset of JSON Schema the contracts use:
object / string / integer / number / boolean / array / $ref to #/definitions / enum.
"""

from __future__ import annotations

import json
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
SCHEMAS = APP.parent / "contracts" / "schemas"
OUT = APP / "lib" / "core" / "models" / "contracts.dart"

# Wire/storage types the app uses. entry-generation.json is the pipeline's LLM schema.
INCLUDE = ["dictionary-entry", "context-result", "translation-result", "phrase-match", "api-error"]
# Dart-side names where the schema title would collide with Flutter's own classes.
RENAME = {"Form": "WordForm"}


def dart_type(prop: dict, defs: dict[str, dict], parent: str, name: str, classes: dict[str, dict]) -> str:
    if "$ref" in prop:
        ref = prop["$ref"].split("/")[-1]
        return RENAME.get(ref, ref)
    t = prop.get("type")
    if t == "string":
        if "enum" in prop:
            enum_name = parent + name[0].upper() + name[1:]
            classes[enum_name] = {"enum": prop["enum"]}
            return enum_name
        return "String"
    if t == "integer":
        return "int"
    if t == "number":
        return "double"
    if t == "boolean":
        return "bool"
    if t == "array":
        return f"List<{dart_type(prop['items'], defs, parent, name, classes)}>"
    if t == "object":
        # Inline object → nested class named after the property.
        cls = parent + name[0].upper() + name[1:]
        classes[cls] = prop
        return cls
    raise ValueError(f"unsupported schema for {parent}.{name}: {prop}")


def emit_class(name: str, schema: dict, defs: dict[str, dict], classes: dict[str, dict]) -> str:
    if "enum" in schema:
        values = ",\n".join(f"  @JsonValue('{v}')\n  {to_camel(v)}" for v in schema["enum"])
        return f"enum {name} {{\n{values},\n}}\n"
    required = set(schema.get("required", []))
    lines = []
    desc = schema.get("description")
    if desc:
        lines.append("/// " + desc.replace("\n", "\n/// "))
    lines.append("@freezed")
    lines.append(f"abstract class {name} with _${name} {{")
    lines.append(f"  const factory {name}({{")
    for prop, spec in schema["properties"].items():
        ty = dart_type(spec, defs, name, prop, classes)
        if prop in required:
            lines.append(f"    required {ty} {prop},")
        else:
            lines.append(f"    {ty}? {prop},")
    lines.append(f"  }}) = _{name};")
    lines.append("")
    lines.append(f"  factory {name}.fromJson(Map<String, dynamic> json) => _${name}FromJson(json);")
    lines.append("}")
    return "\n".join(lines) + "\n"


def to_camel(s: str) -> str:
    parts = s.lower().replace("-", "_").split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def main() -> None:
    out = [
        "// GENERATED by tool/gen_models.py from contracts/schemas — do not edit.",
        "// Regenerate: python3 tool/gen_models.py && dart run build_runner build -d",
        "",
        "import 'package:freezed_annotation/freezed_annotation.dart';",
        "",
        "part 'contracts.freezed.dart';",
        "part 'contracts.g.dart';",
        "",
    ]
    emitted: set[str] = set()
    for stem in INCLUDE:
        schema = json.loads((SCHEMAS / f"{stem}.json").read_text(encoding="utf-8"))
        name = schema["title"]
        defs = schema.get("definitions", {})
        classes: dict[str, dict] = {name: schema}
        # definitions first so nested names are stable, then the root.
        for dn, dschema in defs.items():
            classes[RENAME.get(dn, dn)] = dschema
        pending = list(classes.items())
        while pending:
            cname, cschema = pending.pop(0)
            if cname in emitted:
                continue
            before = set(classes)
            code = emit_class(cname, cschema, defs, classes)
            out.append(code)
            emitted.add(cname)
            for new in set(classes) - before:
                pending.append((new, classes[new]))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT.relative_to(APP)}: {len(emitted)} types")


if __name__ == "__main__":
    main()
